/**
 * 由 src/webui/index.html 生成 src/webui/page.ts（内嵌页面，零静态文件依赖）。
 *
 * 用法：node scripts/gen-page.mjs
 * 从 index.html 按顺序内联 client 模块，最后编码为 JS 字符串常量。
 * 客户端仍为零静态资源请求，但源码可按功能维护，支持普通模板字符串。
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const htmlPath = path.join(root, "src/webui/index.html");
const outPath = path.join(root, "src/webui/page.ts");

const html = fs.readFileSync(htmlPath, "utf8").replace(/\/\* @include ([a-zA-Z0-9_./-]+) \*\//g, (_, file) => {
  const target = path.resolve(root, "src/webui", file);
  if (!target.startsWith(path.join(root, "src/webui/client") + path.sep)) throw new Error("Invalid client module " + file);
  const source = fs.readFileSync(target, "utf8");
  if (/<\/script\s*>/i.test(source)) throw new Error("Client modules cannot contain a literal closing script tag: " + file);
  return source;
});
const header = "/** Generated by scripts/gen-page.mjs from index.html and client modules. Do not edit. */\n";
fs.writeFileSync(outPath, header + "export const PAGE_HTML = " + JSON.stringify(html) + ";\n");
console.log("generated", path.relative(root, outPath), `(${html.length} chars)`);
