/**
 * 由 src/webui/index.html 生成 src/webui/page.ts（内嵌页面，零静态文件依赖）。
 *
 * 用法：node scripts/gen-page.mjs
 * 从 index.html 按顺序内联 client 模块，最后编码为 JS 字符串常量。
 * 客户端仍为零静态资源请求，但源码可按功能维护，支持普通模板字符串。
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { renderWebUISource } from "./webui-source.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outPath = path.join(root, "src/webui/page.ts");
const html = renderWebUISource(root);
const header = "/** Generated by scripts/gen-page.mjs from index.html and client modules. Do not edit. */\n";
fs.writeFileSync(outPath, header + "export const PAGE_HTML = " + JSON.stringify(html) + ";\n");
console.log("generated", path.relative(root, outPath), `(${html.length} chars)`);
